use crate::acp::protocol::{
    AgentInfo, ClientInfo, InitializeRequest, InitializeResponse, JsonRpcMessage,
    SessionNotification,
};
use crate::commands::zed_detection;
use crate::error::{AikiError, Result};
use crate::event_bus;
use crate::events::{
    AikiEvent, AikiPostFileChangeEvent, AikiPostResponseEvent, AikiPrePromptEvent,
};
use crate::provenance::AgentType;
use agent_client_protocol::{
    SessionUpdate, ToolCall, ToolCallId, ToolCallLocation, ToolCallStatus, ToolCallUpdate, ToolKind,
};
use std::collections::HashMap;
use std::io::{self, BufRead, BufReader, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::{mpsc, Arc, Mutex};
use std::thread;

/// A normalized JSON-RPC request/response ID used as a HashMap key
///
/// JSON-RPC IDs can be strings, numbers, or null. This newtype wraps the
/// normalized string representation to ensure type safety when using IDs
/// as HashMap keys.
///
/// # Normalization Rules
/// - String ID "abc" → `JsonRpcId("\"abc\"")`  (with quotes)
/// - Number ID 123 → `JsonRpcId("123")`        (no quotes)
/// - Null ID → `JsonRpcId("null")`
///
/// This matches the behavior of `serde_json::Value::to_string()`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct JsonRpcId(String);

impl JsonRpcId {
    /// Normalize a JSON-RPC ID from a serde_json::Value
    fn from_value(id: &serde_json::Value) -> Self {
        Self(id.to_string())
    }
}

/// State coordination messages sent between proxy threads
/// (IDE→Agent thread sends, Agent→IDE thread owns state)
#[derive(Debug, Clone)]
enum StateMessage {
    /// Client (IDE) information detected from initialize request
    ClientInfo(ClientInfo),
    /// Agent information detected from initialize response
    AgentInfo(AgentInfo),
    /// Working directory from session/new or session/load
    WorkingDirectory(PathBuf),
    /// Session ID from session/prompt request (for PostResponse tracking)
    PromptRequest {
        request_id: serde_json::Value, // Raw JSON-RPC "id" field (normalized at consumption)
        session_id: String,
    },
    /// Clear response accumulator for a session (on new prompt)
    ClearAccumulator { session_id: String },
}

/// A JSON-RPC autoreply message to be sent to the agent
///
/// This wraps a serialized JSON-RPC request that was generated by the
/// PostResponse event handler. The IDE→Agent thread will forward this
/// to the agent's stdin.
#[derive(Debug, Clone)]
struct AutoreplyMessage {
    /// The complete JSON-RPC request as a string (ready to send on stdin)
    json: String,
    /// The request ID for tracking the response
    request_id: JsonRpcId,
}

impl AutoreplyMessage {
    /// Create a new session/prompt autoreply request
    ///
    /// Constructs a JSON-RPC session/prompt request with the given text,
    /// generates a unique request ID, and serializes it.
    ///
    /// # Arguments
    /// * `session_id` - The session ID to send the prompt to
    /// * `autoreply_text` - The text content to send as the prompt
    /// * `counter` - The autoreply counter for this session (for unique ID generation)
    fn new(session_id: &str, autoreply_text: String, counter: usize) -> Result<Self> {
        use serde_json::json;

        // Generate unique request ID
        let autoreply_id = format!("aiki-autoreply-{}-{}", session_id, counter);

        // Construct JSON-RPC session/prompt request
        let autoreply_request = json!({
            "jsonrpc": "2.0",
            "id": &autoreply_id,
            "method": "session/prompt",
            "params": {
                "sessionId": session_id,
                "prompt": [{
                    "type": "text",
                    "text": autoreply_text
                }]
            }
        });

        // Serialize to JSON string
        let json = serde_json::to_string(&autoreply_request).map_err(|e| {
            AikiError::Other(anyhow::anyhow!("Failed to serialize autoreply: {}", e))
        })?;

        // Create normalized request ID
        let request_id = JsonRpcId::from_value(&serde_json::Value::String(autoreply_id));

        Ok(Self { json, request_id })
    }

    /// Get the JSON string to send to the agent
    fn as_json(&self) -> &str {
        &self.json
    }

    /// Get the request ID for tracking the response
    fn request_id(&self) -> &JsonRpcId {
        &self.request_id
    }

    /// Get the raw request ID string for display/debugging
    fn request_id_display(&self) -> &str {
        &self.request_id.0
    }
}

/// Run the ACP bidirectional proxy
///
/// This command acts as a transparent proxy between an IDE (Zed, Neovim, etc.)
/// and an AI agent (claude-code, cursor, gemini, etc.), allowing Aiki to:
/// - Observe agent → IDE messages (tool_call notifications)
/// - Intercept IDE → agent messages (foundation for modification)
/// - Auto-detect the client (IDE) from InitializeRequest
/// - Record provenance with both client_name and agent_type
///
/// # Arguments
/// * `agent_type` - The agent type for provenance tracking (e.g., "claude-code", "cursor")
/// * `bin` - Optional custom binary path (defaults to derived from agent_type)
/// * `agent_args` - Optional arguments to pass to the agent executable
pub fn run(agent_type: String, bin: Option<String>, agent_args: Vec<String>) -> Result<()> {
    // Install panic hook to diagnose crashes - write to file since stderr might be buffered
    std::panic::set_hook(Box::new(|panic_info| {
        use std::io::Write;

        // Try to write to a debug file
        if let Ok(mut file) = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open("/tmp/aiki-proxy-panic.log")
        {
            let _ = writeln!(
                file,
                "\n=== PANIC IN ACP PROXY at {} ===",
                chrono::Utc::now().format("%Y-%m-%d %H:%M:%S")
            );
            let _ = writeln!(file, "{}", panic_info);
            if let Some(location) = panic_info.location() {
                let _ = writeln!(
                    file,
                    "Location: {}:{}:{}",
                    location.file(),
                    location.line(),
                    location.column()
                );
            }
            let _ = writeln!(file, "=== END PANIC ===\n");
            let _ = file.flush();
        }

        // Also write to stderr
        let stderr = std::io::stderr();
        let mut handle = stderr.lock();
        let _ = writeln!(handle, "=== PANIC IN ACP PROXY ===");
        let _ = writeln!(handle, "{}", panic_info);
        if let Some(location) = panic_info.location() {
            let _ = writeln!(
                handle,
                "Location: {}:{}:{}",
                location.file(),
                location.line(),
                location.column()
            );
        }
        let _ = writeln!(handle, "=== END PANIC ===");
        let _ = handle.flush();
    }));

    // Validate agent_type matches our enum
    let validated_agent_type = parse_agent_type(&agent_type)?;

    // Resolve agent binary: use --bin flag if provided, otherwise detect from Zed or PATH
    let (command, command_args) = if let Some(custom_bin) = bin {
        // User provided custom binary path - use it directly
        eprintln!("  Using custom binary: {}", custom_bin);
        (custom_bin, agent_args.clone())
    } else {
        // Auto-detect using Zed detection with PATH fallback
        let resolved = zed_detection::resolve_agent_binary(&agent_type)?;
        let cmd = resolved.command();
        let mut args = resolved.args();
        args.extend(agent_args.clone());
        (cmd, args)
    };

    // Create channel for metadata communication
    // IDE→Agent thread will send discovered metadata
    // Agent→IDE thread will receive and own the state
    let (metadata_tx, metadata_rx) = mpsc::channel::<StateMessage>();

    // Create channel for autoreplies
    // Agent→IDE thread detects PostResponse and sends autoreply requests
    // IDE→Agent thread receives and forwards them to agent
    let (autoreply_tx, autoreply_rx) = mpsc::channel::<AutoreplyMessage>();

    // Launch agent with piped stdin/stdout
    let mut agent = Command::new(&command)
        .args(&command_args)
        .env("AIKI_ENABLED", "true")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| {
            AikiError::Other(anyhow::anyhow!(
                "Failed to spawn command '{}': {}",
                command,
                e
            ))
        })?;

    let agent_stdin = agent.stdin.take().expect(
        "Failed to acquire agent stdin - this should never happen as we set Stdio::piped()",
    );
    let agent_stdout = agent.stdout.take().expect(
        "Failed to acquire agent stdout - this should never happen as we set Stdio::piped()",
    );

    // Thread 1: Autoreply forwarder (dedicated thread to drain autoreply channel)
    // This ensures autoreplies are sent even when IDE is idle
    // Wrap agent_stdin in Arc<Mutex<>> for safe sharing between threads
    let agent_stdin_shared = Arc::new(Mutex::new(agent_stdin));
    let agent_stdin_for_autoreplies = Arc::clone(&agent_stdin_shared);

    let autoreply_thread = thread::spawn(move || -> Result<()> {
        eprintln!("ACP Proxy: Autoreply forwarder thread started");

        // Block on the autoreply channel and forward messages as they arrive
        while let Ok(autoreply_msg) = autoreply_rx.recv() {
            let mut stdin = agent_stdin_for_autoreplies.lock().unwrap();
            if let Err(e) = writeln!(stdin, "{}", autoreply_msg.as_json()) {
                eprintln!("Warning: Failed to send autoreply: {}", e);
                break;
            } else if let Err(e) = stdin.flush() {
                eprintln!("Warning: Failed to flush autoreply: {}", e);
                break;
            } else if std::env::var("AIKI_DEBUG").is_ok() {
                eprintln!(
                    "[acp] Sent autoreply to agent: {} bytes",
                    autoreply_msg.as_json().len()
                );
            }
        }

        if std::env::var("AIKI_DEBUG").is_ok() {
            eprintln!("ACP Proxy: Autoreply forwarder thread exiting");
        }
        Ok(())
    });

    // Thread 2: IDE → Agent (intercept and modify)
    // This thread discovers metadata and sends it via channel
    let metadata_tx_clone = metadata_tx.clone();
    let agent_type_clone = agent_type.clone();
    let agent_stdin_for_ide = Arc::clone(&agent_stdin_shared);
    let ide_to_agent_thread = thread::spawn(move || -> Result<()> {
        let stdin = io::stdin();
        eprintln!("ACP Proxy: IDE → Agent thread started");

        // Track cwd in this thread for PrePrompt events
        let mut thread_cwd: Option<PathBuf> = None;

        for line in stdin.lock().lines() {
            let line = line?;
            // Removed verbose logging to prevent stderr overflow panic

            // Try to parse message from IDE for metadata extraction
            if let Ok(msg) = serde_json::from_str::<JsonRpcMessage>(&line) {
                // Capture metadata from IDE requests
                if let Some(method) = &msg.method {
                    match method.as_str() {
                        "initialize" => {
                            if let Some(params) = &msg.params {
                                if let Ok(init_req) =
                                    serde_json::from_value::<InitializeRequest>(params.clone())
                                {
                                    if let Some(client_info) = init_req.client_info {
                                        // Send full client info to Agent→IDE thread
                                        let _ = metadata_tx_clone
                                            .send(StateMessage::ClientInfo(client_info.clone()));

                                        if let Some(ref ver) = client_info.version {
                                            eprintln!(
                                                "ACP Proxy: Detected client '{}' version '{}' connecting to agent '{}'",
                                                client_info.name, ver, agent_type_clone
                                            );
                                        } else {
                                            eprintln!(
                                                "ACP Proxy: Detected client '{}' connecting to agent '{}'",
                                                client_info.name, agent_type_clone
                                            );
                                        }
                                    }
                                }
                            }
                        }
                        "session/new" | "session/load" => {
                            // Extract working directory from session requests
                            if let Some(params) = &msg.params {
                                if let Some(cwd_str) = params.get("cwd").and_then(|v| v.as_str()) {
                                    let path = PathBuf::from(cwd_str);

                                    // Store in this thread's cwd
                                    thread_cwd = Some(path.clone());

                                    // Send working directory to Agent→IDE thread
                                    let _ = metadata_tx_clone
                                        .send(StateMessage::WorkingDirectory(path));

                                    if std::env::var("AIKI_DEBUG").is_ok() {
                                        eprintln!(
                                            "ACP Proxy: Set working directory to: {}",
                                            cwd_str
                                        );
                                    }
                                }
                            }
                        }
                        "session/prompt" => {
                            // PrePrompt event: intercept and potentially modify prompt
                            if let Some(params) = &msg.params {
                                // Signal Agent→IDE thread to clear response accumulator for this session
                                // This ensures we start fresh for each new prompt, preventing concatenation
                                // of old text if the previous turn ended without end_turn (error, cancel, etc.)
                                // Extract sessionId directly from params (session/prompt doesn't have 'update' field)
                                let session_id = params
                                    .get("sessionId")
                                    .and_then(|v| v.as_str())
                                    .unwrap_or_default()
                                    .to_string();

                                if !session_id.is_empty() {
                                    let _ = metadata_tx_clone
                                        .send(StateMessage::ClearAccumulator { session_id });
                                }

                                // Pass the thread's tracked cwd
                                if let Err(e) = handle_session_prompt(
                                    &agent_stdin_for_ide,
                                    &msg,
                                    params,
                                    &validated_agent_type,
                                    &thread_cwd,
                                    &metadata_tx_clone,
                                ) {
                                    eprintln!("Warning: Failed to handle session/prompt: {}", e);
                                    // On error, forward original message
                                    let mut stdin = agent_stdin_for_ide.lock().unwrap();
                                    writeln!(stdin, "{}", line)?;
                                    stdin.flush()?;
                                }
                                // Skip the normal forwarding since handle_session_prompt already did it
                                continue;
                            }
                        }
                        "authenticate" => {
                            // Just observe and forward - let the agent handle authentication
                            if std::env::var("AIKI_DEBUG").is_ok() {
                                eprintln!("ACP Proxy: Forwarding authenticate request to agent");
                            }
                        }
                        _ => {}
                    }
                }
            }

            // Forward raw line to agent (no re-serialization)
            let mut stdin = agent_stdin_for_ide.lock().unwrap();
            writeln!(stdin, "{}", line)?;
            stdin.flush()?;
        }
        if std::env::var("AIKI_DEBUG").is_ok() {
            eprintln!("ACP Proxy: IDE stdin closed, stopping IDE → Agent thread");
        }
        Ok(())
    });

    // Thread 2: Agent → IDE (observe and record)
    // This thread OWNS all metadata state and receives updates via channel
    let mut client_info: Option<ClientInfo> = None;
    let mut agent_info: Option<AgentInfo> = None;
    let mut cwd: Option<PathBuf> = None;
    let mut tool_call_contexts: HashMap<ToolCallId, ToolCallContext> = HashMap::new();

    // Track prompt requests for PostResponse event
    // Key is JsonRpcId (normalized request_id), value is session_id
    let mut prompt_requests: HashMap<JsonRpcId, String> = HashMap::new();

    // Track autoreply counters per session (not global)
    let mut autoreply_counters: HashMap<String, usize> = HashMap::new();
    const MAX_AUTOREPLIES: usize = 5;

    // Track response text accumulation per request_id for PostResponse
    let mut response_accumulator: HashMap<String, String> = HashMap::new();

    // Run main forwarding loop, capturing any errors
    let loop_result = (|| -> Result<()> {
        eprintln!("ACP Proxy: Agent → IDE thread started");
        for line in BufReader::new(agent_stdout).lines() {
            let line = line?;
            // Removed verbose logging to prevent stderr overflow panic

            // Drain all pending metadata updates from IDE→Agent thread
            while let Ok(msg) = metadata_rx.try_recv() {
                match msg {
                    StateMessage::ClientInfo(info) => {
                        client_info = Some(info);
                    }
                    StateMessage::AgentInfo(info) => {
                        agent_info = Some(info);
                    }
                    StateMessage::WorkingDirectory(path) => {
                        cwd = Some(path);
                    }
                    StateMessage::PromptRequest {
                        request_id,
                        session_id,
                    } => {
                        // Normalize the ID at consumption point to ensure consistent HashMap keys
                        // This handles any JSON-RPC ID format (string, number, null)
                        prompt_requests.insert(JsonRpcId::from_value(&request_id), session_id);
                    }
                    StateMessage::ClearAccumulator { session_id } => {
                        // Clear accumulated response text for this session
                        // This happens on each new prompt to prevent stale text from failed turns
                        response_accumulator.remove(&session_id);
                    }
                }
            }

            // Parse message from agent
            if let Ok(msg) = serde_json::from_str::<JsonRpcMessage>(&line) {
                // Removed verbose logging to prevent stderr overflow panic

                // Capture agent info from initialize response
                if msg.id.is_some() && msg.result.is_some() {
                    if let Some(result) = &msg.result {
                        if let Ok(init_resp) =
                            serde_json::from_value::<InitializeResponse>(result.clone())
                        {
                            if let Some(info) = init_resp.agent_info {
                                if let Some(ref version) = info.version {
                                    eprintln!(
                                        "ACP Proxy: Detected agent '{}' version '{}'",
                                        info.name, version
                                    );
                                }
                                agent_info = Some(info);
                            }
                        }

                        // Check for stopReason (turn completion)
                        if let Some(stop_reason) = result.get("stopReason").and_then(|v| v.as_str())
                        {
                            // PostResponse event: agent finished responding
                            if stop_reason == "end_turn" {
                                if let Some(response_id) = &msg.id {
                                    // Normalize the response ID for HashMap lookup
                                    let request_id = JsonRpcId::from_value(response_id);

                                    // Look up session_id from the original request
                                    if let Some(session_id) = prompt_requests.remove(&request_id) {
                                        // Get accumulated response text for this session
                                        let response_text = response_accumulator
                                            .remove(&session_id)
                                            .unwrap_or_default();

                                        // Fire PostResponse event
                                        if let Err(e) = handle_post_response(
                                            &session_id,
                                            &validated_agent_type,
                                            &cwd,
                                            &response_text,
                                            &mut autoreply_counters,
                                            MAX_AUTOREPLIES,
                                            &autoreply_tx,
                                            &mut prompt_requests,
                                        ) {
                                            eprintln!(
                                                "Warning: Failed to handle PostResponse: {}",
                                                e
                                            );
                                        }
                                    } else if std::env::var("AIKI_DEBUG").is_ok() {
                                        eprintln!(
                                            "[acp] Detected stopReason but no matching request_id: {:?}",
                                            response_id
                                        );
                                    }
                                }
                            }
                        }
                    }
                }

                if let Some(method) = &msg.method {
                    // Handle session/request_permission - fire PreFileChange for file-modifying tools
                    if method == "session/request_permission" {
                        if is_file_modifying_permission_request(&msg) {
                            // Extract session_id from params
                            if let Some(params) = &msg.params {
                                if let Some(session_id) =
                                    params.get("sessionId").and_then(|v| v.as_str())
                                {
                                    // Fire PreFileChange event BEFORE forwarding permission request to IDE
                                    if let Err(e) = fire_pre_file_change_event(
                                        session_id,
                                        &validated_agent_type,
                                        &cwd,
                                    ) {
                                        eprintln!(
                                            "Warning: Failed to fire PreFileChange event: {}",
                                            e
                                        );
                                    }
                                }
                            }
                        }
                    }

                    // Handle session/update messages
                    if method == "session/update" {
                        // Removed verbose logging to prevent stderr overflow panic

                        // Capture response text from agent_message_chunk updates
                        if let Some(params) = &msg.params {
                            if let Ok(notification) =
                                serde_json::from_value::<SessionNotification>(params.clone())
                            {
                                let session_id = notification.session_id.to_string();

                                // Check if this is an agent_message_chunk with text content
                                if let Some(update_obj) =
                                    params.get("update").and_then(|v| v.as_object())
                                {
                                    if update_obj.get("type").and_then(|v| v.as_str())
                                        == Some("agent_message_chunk")
                                    {
                                        if let Some(content) =
                                            update_obj.get("content").and_then(|v| v.as_object())
                                        {
                                            if let Some(text) =
                                                content.get("text").and_then(|v| v.as_str())
                                            {
                                                // Accumulate response text per session
                                                response_accumulator
                                                    .entry(session_id.clone())
                                                    .or_insert_with(String::new)
                                                    .push_str(text);
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        // Record provenance via event bus (non-blocking)
                        if let Err(e) = handle_session_update(
                            &msg,
                            &validated_agent_type,
                            &client_info,
                            &agent_info,
                            &cwd,
                            &mut tool_call_contexts,
                        ) {
                            eprintln!("Warning: Failed to record provenance: {}", e);
                        }
                    }
                }
            }

            // Forward to IDE
            println!("{}", line);
            io::stdout().flush()?;
        }
        Ok(())
    })();

    // Log any errors from the main loop, but don't exit yet - we need cleanup
    if let Err(ref e) = loop_result {
        eprintln!("ACP Proxy: Error in Agent → IDE forwarding: {}", e);
    }

    if std::env::var("AIKI_DEBUG").is_ok() {
        eprintln!("ACP Proxy: Agent stdout closed, stopping Agent → IDE thread");
    }

    // ALWAYS wait for agent process to exit, even if there was an error
    let status_result = agent.wait();
    if let Err(ref e) = status_result {
        eprintln!("ACP Proxy: Failed to wait for agent process: {}", e);
    } else if let Ok(ref status) = status_result {
        let exit_code = status.code().unwrap_or(-1);
        eprintln!("ACP Proxy: Agent process exited with code: {}", exit_code);
        if exit_code == 101 {
            eprintln!(
                "ACP Proxy: EXIT CODE 101 - This is a Rust panic in the AGENT, not the proxy!"
            );
        }
    }

    // CRITICAL: Drop autoreply_tx and metadata_tx to close the channels before joining threads
    // Without this, the forwarder thread blocks forever on recv() and the proxy hangs at shutdown
    drop(autoreply_tx);
    drop(metadata_tx);

    // ALWAYS join the IDE → Agent thread to ensure clean shutdown
    match ide_to_agent_thread.join() {
        Ok(Ok(())) => {
            if std::env::var("AIKI_DEBUG").is_ok() {
                eprintln!("ACP Proxy: IDE → Agent thread exited cleanly");
            }
        }
        Ok(Err(e)) => {
            eprintln!("Warning: IDE → Agent thread returned error: {}", e);
        }
        Err(e) => {
            eprintln!("Warning: IDE → Agent thread panicked: {:?}", e);
        }
    }

    // ALWAYS join the autoreply forwarder thread to ensure clean shutdown
    match autoreply_thread.join() {
        Ok(Ok(())) => {
            if std::env::var("AIKI_DEBUG").is_ok() {
                eprintln!("ACP Proxy: Autoreply forwarder thread exited cleanly");
            }
        }
        Ok(Err(e)) => {
            eprintln!("Warning: Autoreply forwarder thread returned error: {}", e);
        }
        Err(e) => {
            eprintln!("Warning: Autoreply forwarder thread panicked: {:?}", e);
        }
    }

    // Now propagate the original error if there was one
    loop_result?;

    // Exit with agent's exit code, or 1 if we couldn't get it
    let exit_code = status_result.ok().and_then(|s| s.code()).unwrap_or(1);
    std::process::exit(exit_code);
}

/// Parse and validate agent type against our AgentType enum
fn parse_agent_type(agent: &str) -> Result<AgentType> {
    match agent {
        "claude" | "claude-code" => Ok(AgentType::Claude), // Accept both for backwards compatibility
        "codex" => Ok(AgentType::Codex),
        "cursor" => Ok(AgentType::Cursor),
        "gemini" => Ok(AgentType::Gemini),
        _ => Err(AikiError::UnknownAgentType(agent.to_string())),
    }
}

/// Handle session/update notification from agent
///
/// Extracts tool_call information and dispatches provenance recording via event bus.
/// This is called for every session/update from the agent to the IDE.
fn handle_session_update(
    msg: &JsonRpcMessage,
    agent_type: &AgentType,
    client_info: &Option<ClientInfo>,
    agent_info: &Option<AgentInfo>,
    cwd: &Option<PathBuf>,
    tool_call_contexts: &mut HashMap<ToolCallId, ToolCallContext>,
) -> Result<()> {
    // Parse session/update params
    let params = msg
        .params
        .as_ref()
        .ok_or_else(|| AikiError::Other(anyhow::anyhow!("session/update missing params")))?;

    let notification: SessionNotification =
        serde_json::from_value(params.clone()).map_err(|e| {
            AikiError::Other(anyhow::anyhow!(
                "Failed to parse SessionNotification: {}",
                e
            ))
        })?;

    let session_id = notification.session_id.to_string();

    match &notification.update {
        SessionUpdate::ToolCall(tool_call) => process_tool_call(
            &session_id,
            tool_call,
            agent_type,
            client_info,
            agent_info,
            cwd,
            tool_call_contexts,
        ),
        SessionUpdate::ToolCallUpdate(update) => process_tool_call_update(
            &session_id,
            update,
            agent_type,
            client_info,
            agent_info,
            cwd,
            tool_call_contexts,
        ),
        _ => Ok(()),
    }
}

fn process_tool_call(
    session_id: &str,
    tool_call: &ToolCall,
    agent_type: &AgentType,
    client_info: &Option<ClientInfo>,
    agent_info: &Option<AgentInfo>,
    cwd: &Option<PathBuf>,
    tool_call_contexts: &mut HashMap<ToolCallId, ToolCallContext>,
) -> Result<()> {
    let context = ToolCallContext {
        kind: tool_call.kind,
        paths: paths_from_locations(&tool_call.locations),
        content: tool_call.content.clone(),
    };

    let status = tool_call.status;

    // Store context for potential updates
    tool_call_contexts.insert(tool_call.id.clone(), context.clone());
    if matches!(status, ToolCallStatus::Completed | ToolCallStatus::Failed) {
        tool_call_contexts.remove(&tool_call.id);
    }

    if status == ToolCallStatus::Completed {
        record_post_change_events(
            session_id,
            agent_type,
            client_info,
            agent_info,
            cwd,
            context,
        )?;
    }

    Ok(())
}

fn process_tool_call_update(
    session_id: &str,
    tool_call: &ToolCallUpdate,
    agent_type: &AgentType,
    client_info: &Option<ClientInfo>,
    agent_info: &Option<AgentInfo>,
    cwd: &Option<PathBuf>,
    tool_call_contexts: &mut HashMap<ToolCallId, ToolCallContext>,
) -> Result<()> {
    let entry = tool_call_contexts
        .entry(tool_call.id.clone())
        .or_insert_with(|| ToolCallContext {
            kind: tool_call.fields.kind.unwrap_or(ToolKind::Other),
            paths: Vec::new(),
            content: Vec::new(),
        });

    if let Some(kind) = tool_call.fields.kind {
        entry.kind = kind;
    }

    if let Some(locations) = &tool_call.fields.locations {
        entry.paths = paths_from_locations(locations);
    }

    if let Some(content) = &tool_call.fields.content {
        entry.content = content.clone();
    }

    let status = tool_call.fields.status;
    let should_record =
        matches!(status, Some(ToolCallStatus::Completed)) && !entry.paths.is_empty();
    let context = if should_record {
        Some(entry.clone())
    } else {
        None
    };

    if matches!(
        status,
        Some(ToolCallStatus::Completed | ToolCallStatus::Failed)
    ) {
        tool_call_contexts.remove(&tool_call.id);
    }

    if let Some(context) = context {
        record_post_change_events(
            session_id,
            agent_type,
            client_info,
            agent_info,
            cwd,
            context,
        )?;
    }

    Ok(())
}

#[derive(Clone)]
struct ToolCallContext {
    kind: ToolKind,
    paths: Vec<PathBuf>,
    content: Vec<agent_client_protocol::ToolCallContent>,
}

fn paths_from_locations(locations: &[ToolCallLocation]) -> Vec<PathBuf> {
    locations.iter().map(|loc| loc.path.clone()).collect()
}

fn record_post_change_events(
    session_id: &str,
    agent_type: &AgentType,
    client_info: &Option<ClientInfo>,
    agent_info: &Option<AgentInfo>,
    cwd: &Option<PathBuf>,
    context: ToolCallContext,
) -> Result<()> {
    if !matches!(
        context.kind,
        ToolKind::Edit | ToolKind::Delete | ToolKind::Move
    ) {
        return Ok(());
    }

    if context.paths.is_empty() {
        return Ok(());
    }

    // Get working directory (required)
    let working_dir = cwd
        .as_ref()
        .ok_or_else(|| AikiError::Other(anyhow::anyhow!("Working directory not available")))?
        .clone();

    // Extract client info fields (optional)
    let client_name = client_info.as_ref().map(|c| c.name.clone());
    let client_version = client_info.as_ref().and_then(|c| c.version.clone());

    // Extract agent version (optional)
    let agent_version = agent_info.as_ref().and_then(|a| a.version.clone());

    // Get tool name from kind
    let tool_name = format!("{:?}", context.kind); // Convert ToolKind enum to string (Edit, Delete, Move)

    // Convert all paths to strings
    let file_paths: Vec<String> = context
        .paths
        .iter()
        .map(|p| p.to_string_lossy().to_string())
        .collect();

    // Extract edit details from tool call parameters (if available)
    let edit_details = extract_edit_details(&context);

    // Create and dispatch a single event for all affected files
    let event = AikiEvent::PostFileChange(AikiPostFileChangeEvent {
        agent_type: *agent_type,
        client_name: client_name.clone(),
        client_version: client_version.clone(),
        agent_version: agent_version.clone(),
        session_id: session_id.to_string(),
        tool_name: tool_name.clone(),
        file_paths,
        cwd: working_dir.clone(),
        timestamp: chrono::Utc::now(),
        detection_method: crate::provenance::DetectionMethod::ACP,
        edit_details,
    });

    // Dispatch to event bus (non-blocking - errors are logged but don't fail the proxy)
    if let Err(e) = event_bus::dispatch(event) {
        eprintln!("Warning: Event bus dispatch failed: {}", e);
    }

    Ok(())
}

/// Extract edit details from ACP tool call context
///
/// Extracts old_text/new_text from ToolCallContent::Diff variants.
/// The ACP protocol provides file diffs in the content field when tools
/// modify files, allowing us to detect user edits.
fn extract_edit_details(context: &ToolCallContext) -> Vec<crate::events::EditDetail> {
    use agent_client_protocol::ToolCallContent;

    let mut edit_details = Vec::new();

    for content_item in &context.content {
        if let ToolCallContent::Diff { diff } = content_item {
            // Convert PathBuf to string for file_path
            let file_path = diff.path.to_string_lossy().to_string();

            // old_text is Option<String>, use empty string if None (new file)
            let old_string = diff.old_text.clone().unwrap_or_default();

            // new_text is the modified content
            let new_string = diff.new_text.clone();

            edit_details.push(crate::events::EditDetail::new(
                file_path, old_string, new_string,
            ));
        }
    }

    if std::env::var("AIKI_DEBUG").is_ok() && !edit_details.is_empty() {
        eprintln!(
            "[acp] Extracted {} edit details from tool call content",
            edit_details.len()
        );
    }

    edit_details
}

/// Check if a permission request is for a file-modifying tool
///
/// Parses session/request_permission params to determine if the tool
/// will modify files (Edit, Delete, Move). Returns true only for these
/// file-modifying operations, not for read-only tools like Read, Bash, etc.
fn is_file_modifying_permission_request(msg: &JsonRpcMessage) -> bool {
    // Parse the params to extract tool kind
    if let Some(params) = &msg.params {
        // The params should contain toolCallId and potentially tool details
        // We need to check the tool kind from the request
        if let Some(tool_call_id) = params.get("toolCallId") {
            if std::env::var("AIKI_DEBUG").is_ok() {
                eprintln!(
                    "[acp] Found permission request for tool_call_id: {:?}",
                    tool_call_id
                );
            }
        }

        // Try to extract the kind from the permission request
        // The ACP spec shows options array, but we need to check the actual tool details
        // For now, we'll return true if we see certain patterns in the request
        // This may need refinement based on actual ACP permission request structure
        if let Some(kind_val) = params.get("kind").or_else(|| params.get("toolKind")) {
            if let Some(kind_str) = kind_val.as_str() {
                return matches!(kind_str, "edit" | "delete" | "move");
            }
        }
    }

    false
}

/// Handle session/prompt request and fire PrePrompt event
///
/// This intercepts the user's prompt, fires a PrePrompt event, and potentially
/// modifies the prompt before forwarding to the agent. Implements graceful
/// degradation - on any error, forwards the original message.
fn handle_session_prompt(
    agent_stdin: &Arc<Mutex<std::process::ChildStdin>>,
    msg: &JsonRpcMessage,
    params: &serde_json::Value,
    agent_type: &AgentType,
    cwd: &Option<PathBuf>,
    metadata_tx: &mpsc::Sender<StateMessage>,
) -> Result<()> {
    use serde_json::json;

    // Extract session_id
    let session_id = params
        .get("sessionId")
        .and_then(|v| v.as_str())
        .unwrap_or_default()
        .to_string();

    // Extract all text content from prompt array
    let prompt_array = params
        .get("prompt")
        .and_then(|v| v.as_array())
        .ok_or_else(|| AikiError::Other(anyhow::anyhow!("Missing prompt array")))?;

    let mut original_text = String::new();
    for item in prompt_array {
        if item.get("type").and_then(|v| v.as_str()) == Some("text") {
            if let Some(text) = item.get("text").and_then(|v| v.as_str()) {
                if !original_text.is_empty() {
                    original_text.push_str("\n\n");
                }
                original_text.push_str(text);
            }
        }
    }

    // Get working directory with fallback
    let working_dir = cwd
        .as_ref()
        .cloned()
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from("/")));

    // Fire PrePrompt event
    let event = AikiEvent::PrePrompt(AikiPrePromptEvent {
        agent_type: *agent_type,
        session_id: Some(session_id.clone()),
        cwd: working_dir,
        timestamp: chrono::Utc::now(),
        original_prompt: original_text.clone(),
    });

    let response = event_bus::dispatch(event)?;

    // Extract modified_prompt from metadata (use original if not found)
    let modified_prompt = response
        .metadata
        .iter()
        .find(|(k, _)| k == "modified_prompt")
        .map(|(_, v)| v.clone())
        .unwrap_or_else(|| original_text.clone());

    // Modify the JSON params to replace prompt text
    let mut modified_msg = msg.clone();
    if let Some(params_mut) = modified_msg.params.as_mut() {
        if let Some(params_obj) = params_mut.as_object_mut() {
            if let Some(prompt_arr) = params_obj.get_mut("prompt").and_then(|v| v.as_array_mut()) {
                // Find first text item and replace it
                for item in prompt_arr.iter_mut() {
                    if item.get("type").and_then(|v| v.as_str()) == Some("text") {
                        if let Some(item_obj) = item.as_object_mut() {
                            item_obj.insert("text".to_string(), json!(modified_prompt));
                            break;
                        }
                    }
                }
            }
        }
    }

    // Send metadata about this prompt request for PostResponse tracking
    if let Some(request_id) = msg.id.clone() {
        let _ = metadata_tx.send(StateMessage::PromptRequest {
            request_id, // Pass raw Value; normalization happens at consumption
            session_id: session_id.clone(),
        });
    }

    // Forward modified message to agent
    let modified_line = serde_json::to_string(&modified_msg).map_err(|e| {
        AikiError::Other(anyhow::anyhow!(
            "Failed to serialize modified prompt: {}",
            e
        ))
    })?;
    let mut stdin = agent_stdin.lock().unwrap();
    writeln!(stdin, "{}", modified_line)?;
    stdin.flush()?;

    if std::env::var("AIKI_DEBUG").is_ok() {
        eprintln!(
            "[acp] Fired PrePrompt event for session: {}, modified: {}",
            session_id,
            modified_prompt != original_text
        );
    }

    Ok(())
}

/// Handle PostResponse event and autoreply
///
/// Fires when the agent completes a turn (stopReason: end_turn).
/// Dispatches PostResponse event to flows, and if they return an autoreply,
/// sends it back to the agent (up to MAX_AUTOREPLIES times per session).
fn handle_post_response(
    session_id: &str,
    agent_type: &AgentType,
    cwd: &Option<PathBuf>,
    response_text: &str,
    autoreply_counters: &mut HashMap<String, usize>,
    max_autoreplies: usize,
    autoreply_tx: &mpsc::Sender<AutoreplyMessage>,
    prompt_requests: &mut HashMap<JsonRpcId, String>,
) -> Result<()> {
    // Get working directory with fallback
    let working_dir = cwd
        .as_ref()
        .cloned()
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from("/")));

    // Fire PostResponse event with accumulated response text
    let event = AikiEvent::PostResponse(AikiPostResponseEvent {
        agent_type: *agent_type,
        session_id: Some(session_id.to_string()),
        cwd: working_dir,
        timestamp: chrono::Utc::now(),
        response: response_text.to_string(),
        modified_files: Vec::new(), // Files tracked separately via PostFileChange events
    });

    let response = event_bus::dispatch(event)?;

    // Check for autoreply in metadata
    let autoreply = response
        .metadata
        .iter()
        .find(|(k, _)| k == "autoreply")
        .map(|(_, v)| v.clone());

    if let Some(autoreply_text) = autoreply {
        // Get current autoreply count for this session
        let current_count = autoreply_counters.get(session_id).copied().unwrap_or(0);

        if !autoreply_text.is_empty() && current_count < max_autoreplies {
            // Increment counter for this session
            let new_count = current_count + 1;
            autoreply_counters.insert(session_id.to_string(), new_count);

            if std::env::var("AIKI_DEBUG").is_ok() {
                eprintln!(
                    "[acp] PostResponse autoreply #{} for session {}: {} chars",
                    new_count,
                    session_id,
                    autoreply_text.len()
                );
            }

            // Create autoreply message (constructs JSON-RPC request and generates ID)
            let autoreply_msg = AutoreplyMessage::new(session_id, autoreply_text, new_count)?;

            // Track this autoreply request ID for future PostResponse
            prompt_requests.insert(autoreply_msg.request_id().clone(), session_id.to_string());

            // Extract debug info before moving
            let debug_request_id = if std::env::var("AIKI_DEBUG").is_ok() {
                Some(autoreply_msg.request_id_display().to_string())
            } else {
                None
            };

            // Send via channel to IDE→Agent thread
            autoreply_tx.send(autoreply_msg).map_err(|e| {
                AikiError::Other(anyhow::anyhow!("Failed to send autoreply: {}", e))
            })?;

            if let Some(request_id) = debug_request_id {
                eprintln!(
                    "[acp] Queued autoreply #{} for session: {} with request_id: {}",
                    new_count, session_id, request_id
                );
            }
        } else if current_count >= max_autoreplies {
            eprintln!(
                "Warning: Maximum autoreplies ({}) reached for session {}, ignoring autoreply from flow",
                max_autoreplies, session_id
            );
        }
    } else if std::env::var("AIKI_DEBUG").is_ok() {
        eprintln!(
            "[acp] Fired PostResponse event for session: {}, no autoreply",
            session_id
        );
    }

    Ok(())
}

/// Fire PreFileChange event before file-modifying tool executes
///
/// This is called when we intercept a session/request_permission for
/// file-modifying tools (Edit, Delete, Move). It allows flows to stash
/// user edits before the AI starts making changes.
fn fire_pre_file_change_event(
    session_id: &str,
    agent_type: &AgentType,
    cwd: &Option<PathBuf>,
) -> Result<()> {
    // Get working directory (required)
    let working_dir = cwd
        .as_ref()
        .ok_or_else(|| AikiError::Other(anyhow::anyhow!("Working directory not available")))?
        .clone();

    // Create and dispatch PreFileChange event
    let event = AikiEvent::PreFileChange(crate::events::AikiPreFileChangeEvent {
        agent_type: *agent_type,
        session_id: session_id.to_string(),
        cwd: working_dir,
        timestamp: chrono::Utc::now(),
    });

    // Dispatch to event bus (non-blocking - errors are logged but don't fail the proxy)
    if let Err(e) = event_bus::dispatch(event) {
        eprintln!("Warning: PreFileChange event bus dispatch failed: {}", e);
    } else if std::env::var("AIKI_DEBUG").is_ok() {
        eprintln!(
            "[acp] Fired PreFileChange event for session: {}",
            session_id
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_agent_type_valid() {
        assert!(matches!(parse_agent_type("claude"), Ok(AgentType::Claude)));
        assert!(matches!(
            parse_agent_type("claude-code"),
            Ok(AgentType::Claude)
        ));
        assert!(matches!(parse_agent_type("codex"), Ok(AgentType::Codex)));
        assert!(matches!(parse_agent_type("cursor"), Ok(AgentType::Cursor)));
        assert!(matches!(parse_agent_type("gemini"), Ok(AgentType::Gemini)));
    }

    #[test]
    fn test_parse_agent_type_invalid() {
        let result = parse_agent_type("invalid-agent");
        assert!(result.is_err());
        assert!(matches!(
            result.unwrap_err(),
            AikiError::UnknownAgentType(_)
        ));
    }

    // Note: derive_executable tests moved to zed_detection module tests
}
